name: an example workflow

#when should this run

on:
  pull_request:
    branch:
      - main

#what should this do?
jobs:
  example-workflow:
    runs-on: ubuntu-latest
  
  steps:
  - name: Say hello
    run: echo "hello world"
    